### ISSUE TITLE
mismatched version of GLIBC

### ISSUE THREAD

**Issue by manish-kumar-01** [graspnet/anygrasp_sdk#1]
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/xeon199/anygrasp_sdk-main/grasp_detection/gsnet.so)`

OS : Ubuntu 18.04

**Comment by chenxi-wang** [comment]
Hi, we tested the prgram on ubuntu 20.04. Maybe you can change glibc version.

**Comment by manish-kumar-01** [comment]
@chenxi-wang can u please release the binaries compiled on ubuntu 18.04 also?

it is not feasible to upgrade the GLIBC version to 2.29 in ubuntu 18.04 as it will break other packages (because of dependencies).

**Comment by chenxi-wang** [comment]
@manish-kumar-01 I sent a new version to your email.

**Comment by kiwiwan** [comment]
> @manish-kumar-01 I sent a new version to your email.

I have the same problem. Could you sent me a 18.04 version to me(183934863@qq.com)? Thanks a lot!

**Comment by Xiong-qi** [comment]
I have the same problem. Could you sent me a Ubuntu 18.04.6 LTS version to me([183934863@qq.com](mailto:1224571102@qq.com))? Thanks a lot!

**Comment by Xiong-qi** [comment]
> @manish-kumar-01 I sent a new version(版本) to your email.

I have the same problem. Could you sent me a Ubuntu 18.04.6 LTS version to me([1224571102@qq.com](mailto:1224571102@qq.com))? Thanks a lot!

**Comment by sjauhri** [comment]
> @manish-kumar-01 I sent a new version to your email.
Hi, I also have the same issue. Could you send the Ubuntu 18 version to me (snehal.jauhri@tu-darmstadt.de)? Thanks in advance!

**Comment by chenxi-wang** [comment]
Hi all, the sdk requires Ubuntu>=20.04 due to the GLIBC verision. I've tried to compile a 18.04 version, but unfortunately, another error occurred which could hardly be fixed. So it is better to switch your machine or upgrade your OS.
