### ISSUE TITLE
Missing the pkgs of model weights in running demo.sh

### ISSUE THREAD

**Issue by sensorwu** [graspnet/anygrasp_sdk#10]
Hello, I tried to run the grasp_detection demo, but got this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'log/checkpoint_detection.tar'`

I find that I miss the message in README.md that "Put model weights under ``log/``."

But I have found no pkgs of model weights in the diretory.
Have I need to train dataset by myself? Or I miss it in other dir?

Thanks for your help

**Comment by kiwiwan** [comment]
You could download them at [checkpoint-rs.tar](https://drive.google.com/file/d/1hd0G8LN6tRpi4742XOTEisbTXNZ-1jmk/view)，[checkpoint-kn.tar](https://drive.google.com/file/d/1vK-d0yxwyJwXHYWOtH1bDMoe--uZ2oLX/view)。Reference [graspnet-baseline](https://github.com/graspnet/graspnet-baseline).

**Comment by chenxi-wang** [comment]
Hi, the model weights are provided together with the license.

**Comment by sensorwu** [comment]
> Hi, the model weights are provided together with the license.

Hi, I found only 4 files under the license dir:
       xxx.lic, xxx.public_key, xxx.signature, licenseCfg.json.
And only license.zip was attached in the last email by Haoshu.

**Comment by chenxi-wang** [comment]
> Hi, I found only 4 files under the license dir: xxx.lic, xxx.public_key, xxx.signature, licenseCfg.json. And only license.zip was attached in the last email by Haoshu.

Sorry, I missed it. Now you can get the weights by the email I just sent.
