### ISSUE TITLE
怎么获得license?

### ISSUE THREAD

**Issue by 1358467720** [graspnet/anygrasp_sdk#14]
我填写了表格，但是一直没有受到回复

**Comment by chenxi-wang** [comment]
请提供您填写的邮箱，我检查一下

**Comment by 1358467720** [comment]
1358467720@qq.com 应该是这个

**Comment by chenxi-wang** [comment]
重新发了一遍，如果还没收到可以看看垃圾箱

**Comment by 1358467720** [comment]
谢谢！收到了，是我没看到，不好意思啦！

**Comment by fly7475123** [comment]
> 请提供您填写的邮箱，我检查一下
您好，我也填了申请表单，麻烦您发我一份license吧，747513190@qq.com。非常感谢！
