### ISSUE TITLE
没收到license

### ISSUE THREAD

**Issue by ypx19** [graspnet/anygrasp_sdk#15]

**Comment by ypx19** [comment]
我填写了表格,但好像没收到license,我的邮箱是 2793400367@qq.com

**Comment by chenxi-wang** [comment]
刚刚重新发了一份过去，现在有收到吗

**Comment by ypx19** [comment]
已收到，谢谢！

发自我的iPhone

**Comment by ypx19** [comment]
请问checkpoint有开源的吗??我之前申请用的主机号所属的主机没有显卡,这两天配环境的时候才发现需要用到显卡,请问我可以再申请另一个机器上的license吗?
------------------&nbsp;原始邮件&nbsp;----------------
发件人:                                                                                                                        "graspnet/anygrasp_sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [graspnet/anygrasp_sdk] 没收到license (Issue #15)





 
刚刚重新发了一份过去，现在有收到吗

**Comment by chenxi-wang** [comment]
> 请问checkpoint有开源的吗??我之前申请用的主机号所属的主机没有显卡,这两天配环境的时候才发现需要用到显卡,请问我可以再申请另一个机器上的license吗? 

可以的，序列号直接发到邮箱 wcx1997@sjtu.edu.cn
