### ISSUE TITLE
about ros dependency 

### ISSUE THREAD

**Issue by Leetaegyeom** [graspnet/anygrasp_sdk#21]
when i run demo.sh, i encounter this issue 

WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable

and my open3d is no responding. how can i fix this issue ??

**Comment by chenxi-wang** [comment]
The warnings do not matter. You can test your Open3d package independently and check whether it runs successfully when drawing a simple shape.
