### ISSUE TITLE
max_gripper_width seems not to constrain the actual grasp width

### ISSUE THREAD

**Issue by elenacliu** [graspnet/anygrasp_sdk#22]
Thank you for you excellent work!

I have just run your grasp_detection demo, and set the max_gripper_width to be 0.08, but I found the output grasp's width is actually about 0.11, which exceeds the max joint limit.

**Comment by chenxi-wang** [comment]
Hi, the problem has been found. Binary files will be updated later.

**Comment by chenxi-wang** [comment]
The binary files have been updated. You can test the new sdk :)
