### ISSUE TITLE
machine ID changed after connecting with kinova manipulation 

### ISSUE THREAD

**Issue by isabella4444x** [graspnet/anygrasp_sdk#24]
您好！我发现只要我的电脑连上kinova机械臂就会报错，用license checker查发现序列号变了，如果不连机械臂就序列号就没问题，请问这个怎么解决呢？谢谢！！！

**Comment by chenxi-wang** [comment]
新的license发到邮箱了，现在解决了吗

**Comment by isabella4444x** [comment]
解决了，谢谢！

----- 原始邮件 -----
发件人: "Chenxi Wang" ***@***.***>
收件人: "graspnet/anygrasp_sdk" ***@***.***>
抄送: "isabella4444x" ***@***.***>, "Author" ***@***.***>
发送时间: 星期三, 2023年 10 月 11日 上午 11:54:32
主题: Re: [graspnet/anygrasp_sdk] machine ID changed after connecting with kinova manipulation  (Issue #24)

新的license发到邮箱了，现在解决了吗
