### ISSUE TITLE
how to set `lims` in grasp_detection demo.py

### ISSUE THREAD

**Issue by elenacliu** [graspnet/anygrasp_sdk#25]
I'm a little confused about the `lims` attribute:

https://github.com/graspnet/anygrasp_sdk/blob/27b09a9de6d631939da519daea4300480557ce25/grasp_detection/demo.py#L33-L54

It says `lims` is workspace limit. But it seems it is passed into `angrasp.get_grasp`, and the point cloud that is passed into it is under camera frame. So how do you set `lims`, is it under camera frame or under world frame?

**Comment by chenxi-wang** [comment]
It's under camera frame.

**Comment by SanMumumu** [comment]
Could you explain the detailed the process of setting `lims`? Thank you!!!!!!!!!!!!!!!!
