### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by manish-kumar-01** [graspnet/anygrasp_sdk#3]
RuntimeError: CUDA out of memory. Tried to allocate 528.00 MiB (GPU 0; 1.95 GiB total capacity; 895.74 MiB already allocated; 385.38 MiB free; 990.00 MiB reserved in total by PyTorch)

I tried running `sh demo.sh` in grasp_detection with NVIDIA  Quadro P600 ( 2GB )
Cuda is getting out of memory.

Is there any alternative, or what is the ideal GPU for this (minimum requirement)?

**Comment by chenxi-wang** [comment]
In most cases 2.5GB is OK. You can try running the program with GPU memory > 3GB.
