### ISSUE TITLE
A request for detailed results on Graspnet-1Billion Dataset

### ISSUE THREAD

**Issue by ChenThree** [graspnet/anygrasp_sdk#34]
Is there the original data (or part of them @top50 grasp, the same metrics in the Graspness paper) in Fig.13 and Fig.16 in your paper?
![1701785382(1)](https://github.com/graspnet/anygrasp_sdk/assets/36262585/12e7f4a8-b855-4fd3-a222-9de3fac37b02)
I found it hard to get the accurate number from the raw image. Or are they the same as those in in the Graspness paper?

**Comment by Fang-Haoshu** [comment]
Hi, if you still need it, please send me an email

**Comment by huamo555** [comment]
> Hi, if you still need it, please send me an email



> Is there the original data (or part of them [@top50](https://github.com/top50) grasp, the same metrics in the Graspness paper) in Fig.13 and Fig.16 in your paper? ![1701785382(1)](https://github.com/graspnet/anygrasp_sdk/assets/36262585/12e7f4a8-b855-4fd3-a222-9de3fac37b02) I found it hard to get the accurate number from the raw image. Or are they the same as those in in the Graspness paper?

Have you received the data from the author? I need this data now too.
