### ISSUE TITLE
Is it possible to run without GPU?

### ISSUE THREAD

**Issue by TKroos18** [graspnet/anygrasp_sdk#4]
Hello, I want to run it on Intel NUC 12. There is only CPU on NUC12. So is it possible to run without GPU?

**Comment by chenxi-wang** [comment]
Sorry, the CPU-only version is not supported.

**Comment by lunalulu** [comment]
hello, can anygrasp run on a nvidia NX ?

**Comment by Fang-Haoshu** [comment]
Hi, we have not tried the Nvidia NX. But if it supports cuda, pytorch and minkowski-engine, I think you can have a try
