### ISSUE TITLE
How to get more grasps in grasp_detection?

### ISSUE THREAD

**Issue by yxKryptonite** [graspnet/anygrasp_sdk#41]
Hi there, thanks for your work!

I am wondering how to get more grasp proposals. Because for now I want to get a grasp that is close to a given 3D point, but often anygrasp cannot output enough grasps that satisfy the distance. Are there any thresholds to get more grasps?

Thanks!

**Comment by chenxi-wang** [comment]
Hi, we just updated the dense_grasp mode, and you can have a try.
