### ISSUE TITLE
Incorrect setup.py for pointnet2

### ISSUE THREAD

**Issue by Gandinator123** [graspnet/anygrasp_sdk#45]
I believe in `pointnet2/setup.py` has an error in **_line 20_**: it should be `packages` not `pacakges`. 

Could the repo be updated please? I would like to use this in a docker container and it is not possible to do this fix and install the dependencies from my dockerfile well. 

Thanks

**Comment by chenxi-wang** [comment]
Hi, the error has been fixed.

**Comment by Kaivalya192** [comment]
hey @Gandinator123 ..
can you share dockerfile please..
since the envirment is so complicated.
