### ISSUE TITLE
there are two same keywords named "pacakges" in pointnet2/setup.py in commitId: 6a0c68c

### ISSUE THREAD

**Issue by zhanghengsjtu** [graspnet/anygrasp_sdk#49]
In the latest updage(commitId: 6a0c68c), there are two same keywords named "pacakges" [pointnet2/setup.py], which will lead to failure to pointnet2 package.

**Comment by chenxi-wang** [comment]
I modified the setup.py in pointnet2 ude to [this issue](https://github.com/graspnet/anygrasp_sdk/issues/45#issue-2244222986). You can change it back for a temporary solution. I'll fix it in a few days.

**Comment by chenxi-wang** [comment]
Hi, the error has been fixed. Thank you for reporting this issue :)
