### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MaximeBinot** [graspnet/anygrasp_sdk#5]
Hello,
I am trying to install the sdk in order to test the detection module with a realsense 435i.

I have a small problem during the second part of the installation related to pointnet2. When trying to execute the install command I get this error :

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
```

The strange thing is that pytorch is installed and if I try to reinstall it with pip I get this message : 

```
pip install torch
Requirement already satisfied: torch in /home/ubuntu/.local/lib/python3.8/site-packages (1.12.1+cu102)
Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from torch) (4.5.0)
```

I even tried with a force reinstall but this doesn't change anything.

I guess I can't use the sdk properly without completing this step so if anyone has a solution it would be a great help.

Thanks

**Comment by chenxi-wang** [comment]
That seems not to be a torch issue, maybe your pip points to a wrong python?
Besides, I remember that there may be a compilation error with pytorch 1.12.1. You may need to change a few lines in src files, or use an older pytorch version (1.9 is OK).
