### ISSUE TITLE
No response to License Application

### ISSUE THREAD

**Issue by junyaoshi** [graspnet/anygrasp_sdk#51]
Hi, I applied for a license a while ago and haven't gotten any response yet. My email is junys@seas.upenn.edu.

Any updates would be greatly appreciated, thanks!

**Comment by chenxi-wang** [comment]
Hi, I've sent the license. Did you check the spam?

**Comment by junyaoshi** [comment]
> Hi, I've sent the license. Did you check the spam?

It went to the spam folder indeed. Thank you!
