### ISSUE TITLE
关了检测和跟踪的一些疑问?

### ISSUE THREAD

**Issue by pange1802703882** [graspnet/anygrasp_sdk#52]
您好，请问我在阅读论文和看代码中有一些疑惑: 加入的时间关联模块是只在跟踪过程中才有效吗？而且看您的代码跟踪的id选择的是0，也就是置信度最高的score，那这个初始的最高位姿是不是仅仅是从gsnet中得到的结果呢?

**Comment by chenxi-wang** [comment]
第一帧从抓取模型结果中根据你的需求和机械臂运动限制选取，不一定选置信度最高的，后面的每一帧跟踪都用到了时间关联模块，demo代码只是为了展示用法
