### ISSUE TITLE
About License Registration

### ISSUE THREAD

**Issue by mustang2247** [graspnet/anygrasp_sdk#55]
project:
"Due to the IP issue, currently we can only release the SDK library file of AnyGrasp in a licensed manner. Please get the feature id of your machine and fill in the [form](https://forms.gle/XVV3Eip8njTYJEBo6) to apply for the license. See [license_registration/README.md](https://github.com/graspnet/anygrasp_sdk/blob/main/license_registration/README.md) for details. If you are interested in code implementation, you can refer to our [baseline version of network](https://github.com/graspnet/graspnet-baseline), or a third-party implementation of our [GSNet](https://github.com/graspnet/graspness_unofficial)."

reply:
![WX20240608-113830@2x](https://github.com/graspnet/anygrasp_sdk/assets/1620402/3ebb6a87-c161-4f90-a748-8a38391e187b)

So
Firstly, I declare that we are conducting scientific research. After we applied, you requested that the school apply, which is a very unreasonable requirement. So your project does not need to be open source, there is no need! Please do not use the guise of open source!

**Comment by Fang-Haoshu** [comment]
Please behavior well.  You don’t have to apply for it, but don’t be rude. Your behavior is always documented.

**Comment by mustang2247** [comment]
"Your behavior is always documented." Is this a threat?
