### ISSUE TITLE
./license_checker -f  error

### ISSUE THREAD

**Issue by yu3jun** [graspnet/anygrasp_sdk#56]
Hi,
I encountered some error when I try to get the feature id using the license_checker
At first I encountered this error:
`./license_checker: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
then I followed the instruction from [https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory](url) installed `libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb`
However a new error showed up:
`sh: 1: ifconfig: not found`
`xargs: ifconfig: No such file or directory`
`Segmentation fault (core dumped)`

My system is Ubuntu 22.04, and I have installed all your requirements follow the readme instructions.

Thanks a lot for your contributions, looking forward to your answers.

**Comment by yu3jun** [comment]
I used `apt install install net-tools` to solve the `sh: 1: ifconfig: not found` error

**Comment by zhirui-gao** [comment]
> I used `apt install install net-tools` and solved the `sh: 1: ifconfig: not found` error

I used 
```
sudo apt install net-tools
```
