### ISSUE TITLE
No response to License Application

### ISSUE THREAD

**Issue by yu3jun** [graspnet/anygrasp_sdk#57]
Hi, I applied for a license a while ago and haven't gotten any response yet. 
My email is [tyj9556@gmail.com] / [2112233104@e.gzhu.edu.cn]
Any updates would be greatly appreciated, thanks!

**Comment by dayong233** [comment]
I also encountered the same problem. I submitted the application on June 12.
My email address is [dayong233@gmail.com] / [22325004@zju.edu.cn]
Looking forward to hearing from you!
