### ISSUE TITLE
Python 3.8.19 Error

### ISSUE THREAD

**Issue by omarrayyann** [graspnet/anygrasp_sdk#59]
<img width="882" alt="Screenshot 2024-06-21 at 1 47 24 AM" src="https://github.com/graspnet/anygrasp_sdk/assets/77675540/855e1a10-71a9-4fed-8eaf-ce6d5f31c6b8">

**Comment by woshiwangye** [comment]
I have the same problem. Have you solved it?

**Comment by omarrayyann** [comment]
@woshiwangye Yes, try `pip install numpy<1.24`
