### ISSUE TITLE
ModuleNotFoundError: No module named 'gsnet'

### ISSUE THREAD

**Issue by airobot1024** [graspnet/anygrasp_sdk#60]
Hi, I encounted two issues when I use anyGrasp project.
In grasp_detection/demo.py,  "from gsnet import AnyGrasp",
when I run the code, the terminal outputs the bellow error:
    ModuleNotFoundError: No module named 'gsnet'

Where is the **gsnet**  module? 

In addition, where is the **tracker** module in grasp_tracking/demo.py?

**Comment by nilupul-tsukarm** [comment]
@airobot1024 I have same issue here .. did you solved ?

**Comment by airobot1024** [comment]
> @airobot1024 I have same issue here .. did you solved ?

I haven't addressed this issue.

**Comment by nilupul-tsukarm** [comment]
@airobot1024 I guess the reason is license registration,  after I doing this https://github.com/graspnet/anygrasp_sdk/tree/7a37b4244112f44e291bccedca88814284467ec5/grasp_detection
    cp gsnet_versions/gsnet.cpython-36m-x86_64-linux-gnu.so gsnet.so
    cp ../license_registration/lib_cxx_versions/lib_cxx.cpython-36m-x86_64-linux-gnu.so lib_cxx.so
ModuleNotFoundError: No module named 'gsnet' problem solved and now encountering 
<img width="419" alt="image" src="https://github.com/graspnet/anygrasp_sdk/assets/165229279/8fe4494c-eafc-41d9-a385-127f9c9fb964">

**Comment by airobot1024** [comment]
> @airobot1024 I guess the reason is license registration, after I doing this https://github.com/graspnet/anygrasp_sdk/tree/7a37b4244112f44e291bccedca88814284467ec5/grasp_detection cp gsnet_versions/gsnet.cpython-36m-x86_64-linux-gnu.so gsnet.so cp ../license_registration/lib_cxx_versions/lib_cxx.cpython-36m-x86_64-linux-gnu.so lib_cxx.so ModuleNotFoundError: No module named 'gsnet' problem solved and now encountering <img alt="image" width="419" src="https://private-user-images.githubusercontent.com/165229279/341652094-8fe4494c-eafc-41d9-a385-127f9c9fb964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTA2MzMsIm5iZiI6MTcxODk1MDMzMywicGF0aCI6Ii8xNjUyMjkyNzkvMzQxNjUyMDk0LThmZTQ0OTRjLWVhZmMtNDFkOS1hMzg1LTEyN2Y5YzlmYjk2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNjEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTVjNTQ4YWZkZmM0YTBjMDIxNTU5Mzg3ZGNjYTkwYTFjYTY0MDcwNzRmMjVlNTgwYmQyNjg2YjFmYjc2ZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oo2J2oqBPq6sZQ-xtZhptaHqcAdHxrVKGyozjk_QFF0">

I think so. Why does your license failed? 
I haven't received the license after filled the register page yesterday.

**Comment by nilupul-tsukarm** [comment]
I also did not received license yet. I'm waiting for that..  here I used sample license folder for just test.  will see..

**Comment by chenxi-wang** [comment]
@airobot1024 Did you receive the license now? I found another application that has the same feature id as yours, and guesses you two are from the same team. Let me know if I made a mistake.

**Comment by chenxi-wang** [comment]
@nilupul-tsukarm Did you receive the license now? If not, tell me your email filled in the google form.

**Comment by nilupul-tsukarm** [comment]
@chenxi-wang yes I received the license at 22/6 by email. Thank you very much. Also i and @airobot1024 are not a same team. 
I filled google form. As well as I sent a reminding email to you. Thanks again for this great work and your all effort.

**Comment by Leeviber** [comment]
> @airobot1024 I guess the reason is license registration, after I doing this https://github.com/graspnet/anygrasp_sdk/tree/7a37b4244112f44e291bccedca88814284467ec5/grasp_detection cp gsnet_versions/gsnet.cpython-36m-x86_64-linux-gnu.so gsnet.so cp ../license_registration/lib_cxx_versions/lib_cxx.cpython-36m-x86_64-linux-gnu.so lib_cxx.so ModuleNotFoundError: No module named 'gsnet' problem solved and now encountering <img alt="image" width="419" src="https://private-user-images.githubusercontent.com/165229279/341652094-8fe4494c-eafc-41d9-a385-127f9c9fb964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcwMDIsIm5iZiI6MTcyMTgwNjcwMiwicGF0aCI6Ii8xNjUyMjkyNzkvMzQxNjUyMDk0LThmZTQ0OTRjLWVhZmMtNDFkOS1hMzg1LTEyN2Y5YzlmYjk2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNzM4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjM2ZjAwYTZjOTEwNGM4OGRlOTQ4N2QxYzExZmI3ZGI4MzFjZTE0YzNkMTAzNGM0NDg5MTM2ZTk5ZjliYzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eu0uK26nklRrqa4vMYflcZ2KwgbUVLbd5ocsXnzR4Qc">

I met the same issue, but I already passed the license check and follow the graspe_detection guide to copy the lib, whenever I tried to ` from gsnet import AnyGrasp`
It will failed with the 
```
2024-07-24 15:35:56.056] [error] [FlexivLic] cfg file doesn't exists!
license passed: False, state: FvrLicenseState.FAILED
[ERROR] license failed to pass!
```
Does anyone solved this before?
