### ISSUE TITLE
Diffrence in anygrasp , unofficial graspness and graspnet baseline model?

### ISSUE THREAD

**Issue by Kaivalya192** [graspnet/anygrasp_sdk#69]
can you tell what pro and cons of it?
supports grasp detection and tracking?

**Comment by chenxi-wang** [comment]
"graspnet-baseline" is the baseline model of [GraspNet-1Billion dataset](https://openaccess.thecvf.com/content_CVPR_2020/papers/Fang_GraspNet-1Billion_A_Large-Scale_Benchmark_for_General_Object_Grasping_CVPR_2020_paper.pdf).
We then proposed [GSNet](https://arxiv.org/abs/2406.11142) which utilizes graspness to provide more diverse grasps and significantly outperforms the baseline method. "graspness_unofficial" is a third-party implementation of it.
Based on GSNet, [AnyGrasp](https://arxiv.org/abs/2212.08333) proposed a more powerful and robust grasp detection model and an efficient grasp tracking model. You can refer to our papers for details.
