### ISSUE TITLE
The 'sklearn' PyPI package is deprecated

### ISSUE THREAD

**Issue by TKroos18** [graspnet/anygrasp_sdk#7]
Hello, I would like to run it on WSL2. When I ran pip install r requirements. txt, I found that it prompted： The 'sklearn' PyPI package is deprecated, using 'scikit learn' compared to 'sklearn' for pip commands.
The whole log is:
anygrasp_sdk$ pip install -r requirements.txt
Requirement already satisfied: numpy in /home/cqsubuntu/.conda/envs/anygrasp_env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.24.2)
Requirement already satisfied: Pillow in /home/cqsubuntu/.conda/envs/anygrasp_env/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: scipy in /home/cqsubuntu/.conda/envs/anygrasp_env/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.10.1)
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting graspnetAPI
  Using cached graspnetAPI-1.2.10.tar.gz (82 kB)
  Preparing metadata (setup.py) ... done
Collecting open3d
  Using cached open3d-0.17.0-cp38-cp38-manylinux_2_27_x86_64.whl (420.5 MB)
Collecting transforms3d==0.3.1
  Using cached transforms3d-0.3.1.tar.gz (62 kB)
  Preparing metadata (setup.py) ... done
Collecting trimesh
  Using cached trimesh-3.21.5-py3-none-any.whl (680 kB)
Collecting opencv-python
  Using cached opencv_python-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.8 MB)
Collecting matplotlib
  Using cached matplotlib-3.7.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
Collecting pywavefront
  Using cached PyWavefront-1.3.3-py3-none-any.whl (28 kB)
Collecting scikit-image
  Using cached scikit_image-0.20.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.4 MB)
Collecting autolab_core
  Using cached autolab_core-1.1.1-py3-none-any.whl (116 kB)
Collecting autolab-perception
  Using cached autolab_perception-1.0.0-py3-none-any.whl (33 kB)
Collecting cvxopt
  Using cached cvxopt-1.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Collecting dill
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting h5py
  Using cached h5py-3.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Collecting sklearn
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
So what should I do?

**Comment by chenxi-wang** [comment]
It seems to be a Windows issue according to https://twitter.com/scikit_learn/status/1597178713896284161. You can try `pip install scikit-learn` instead.

**Comment by Axi404** [comment]
Try `export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True`
