### ISSUE TITLE
license response

### ISSUE THREAD

**Issue by Udntknwme** [graspnet/anygrasp_sdk#75]
hi! thanks for the great work.

I have been apply for the license within two workdays, but have not recieve a license yet.

is there anything wrong?

thanks for the great work again.

**Comment by chenxi-wang** [comment]
Hi, have you received the license yet? If not, please provide your email so that I can make a check.

**Comment by jonghyeon-seon** [comment]
I also applied for the license about two weeks ago but haven't received it yet.

Could you check mine as well?

Thank you.

sunutf@gmail.com is my email

**Comment by chenxi-wang** [comment]
> I also applied for the license about two weeks ago but haven't received it yet.
> 
> Could you check mine as well?
> 
> Thank you.
> 
> [sunutf@gmail.com](mailto:sunutf@gmail.com) is my email

Hi @jonghyeon-seon , I sent the license about two weeks ago. Could it be in the spam folder?

**Comment by jonghyeon-seon** [comment]
I just found that the license you sent was in the spam folder.

Sorry for the confusion.
