### ISSUE TITLE
License Registration and use on non-linux OS

### ISSUE THREAD

**Issue by RAraghavarora** [graspnet/anygrasp_sdk#76]
Hi, is it possible to use AnyGrasp on MacOS? 
While trying to run `./license_checker -f`, I get the following error:

`bash: ./license_checker: cannot execute binary file: Exec format error`.

I tried it on mac, and on a virtualmachine running ubuntu. Is this an OS issue? Please let me know if there is a workaround.
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/5dfdb042-0355-4570-b5d4-266d17b7fd07">

**Comment by chenxi-wang** [comment]
Hi, the sdk does not support MacOS and I'm not clear whether it is Okay to run it in virtual machine. We only tested it on Linux.

**Comment by RAraghavarora** [comment]
Thank you for the response!
