### ISSUE TITLE
license response

### ISSUE THREAD

**Issue by chungmin99** [graspnet/anygrasp_sdk#80]
Hi, thank you for your amazing work!

It has been almost a month(!) since I inquired about the license, but I haven't received a response yet. Could you kindly let me know how I can follow up or if there's anything further I need to do to receive the necessary information?

**Comment by chenxi-wang** [comment]
Hi Chungming, I sent the license on Oct. 10th. Could it be in your spam folder?

**Comment by chungmin99** [comment]
Hi!! Just checked it again -- I see it, I had to just scroll back more! Sorry about that.
