### ISSUE TITLE
How can I get the .zip after applying the license

### ISSUE THREAD

**Issue by sensorwu** [graspnet/anygrasp_sdk#9]
Hello, 
I am trying to install the sdk in order to test the detection module with the UR and a realsense 435.
I have fill out the form for License Registration by huachang_wu@163.com.
But there is no .zip file that contains license return. Is that in the form, or in the email sent to me when I finished the form?
It seems to need to be used in two demon.
Thanks

**Comment by kiwiwan** [comment]
> Hi，your work is so excellent!
I also want to test this sdk. I have fill out the form for License Registration by **kiwiwan8@gmail.com**.
Could you also send me a .zip file that contains license. Thanks a lot.

**Comment by chenxi-wang** [comment]
> Hi，your work is so excellent!
> I also want to test this sdk. I have fill out the form for License Registration by **[kiwiwan8@gmail.com](mailto:kiwiwan8@gmail.com)**.
> Could you also send me a .zip file that contains license. Thanks a lot.

@kiwiwan Hi, I just sent you an email.

**Comment by Murkey8895** [comment]
Hi, I also want to use this awesome SDK. I have filled out the form for License Registration by [keymo.work@gmail.com](mailto:keymo.work@gmail.com), but I didn't get any return. Could you please help me check this out? Thank you very much!
